### ISSUE TITLE
Gyro Functionality not working with FCS (?)

### ISSUE THREAD

**Issue by Oksisane** [lasarobotics/FTCLibs#11]
@gerrycocco @smo-key Top priority to fix in terms of code.

**Comment by Oksisane** [comment]
@smo-key @gerrycocco FINALLY FIXED AT CONNALLY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by smo-key** [comment]
@Oksisane So we think... if this ever happens again....
